config/routes.rb
MusicV20::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

  devise_for :users

  root :to => 'home#index'

   resources :artists do
    member do
      get 'albums'
    end
  end
   resources :albums
 
   resources :users
     resources :libraries do
       resources :playlists do
         resources :comments
       end
    resources :tracks do
    end
   end

   resources :friendships do
     collection do
       get :accept, :decline, :cancel, :delete
     end
     member do
       get :friend_request
     end
   end

  match '/search' => 'search#search', :as => 'search'

  match '/libraries/:id/land' => 'tracks#land', :as => 'land'

end

app/models/track.rb
# require 'taglib'
require "mp3info"
class Track < ActiveRecord::Base

  attr_accessible :bpm, :length, :size, :title, :track_number, :track_location, :user_id, :year, :library_id, :album_id

  include Rails.application.routes.url_helpers
  include ActionDispatch::Routing::UrlFor
  mount_uploader :track_location, TrackLocationUploader

  belongs_to :user
  # belongs_to :playlist
  # belongs_to :artist
  belongs_to :library
  belongs_to :album
  belongs_to :genre

  # has_many :libraries, :through => :track_libraries
  # has_many :track_libraries
  has_many :playlists, :through => :playlist_tracks
  has_many :playlist_tracks
  has_many :artists, :through => :artist_tracks
  has_many :artist_tracks
  # has_many :albums, :through => :album_tracks
  # has_many :album_tracks
  # has_one :album


  letsrate_rateable "rating"


  accepts_nested_attributes_for :artists
  accepts_nested_attributes_for :album
  # accepts_nested_attributes_for :genre

  def parse_id3(data)
    x = "public"+track_location.to_s
    Mp3Info.open(x) do |f|
      self.title = f.tag2["TIT2"]
      self.bpm = f.tag2["TBPM"]
      self.year = f.tag2["TYER"]
      self.track_number = f.tag2["TRCK"]
      self.length = f.length.to_i
      self.size = (self.track_location.file.size.to_f/(1000*1000)).round(2)
      self.album = Album.find_or_create_by_name(f.tag2["TALB"])
      self.album.artist = Artist.find_or_create_by_name(f.tag2["TPE2"])
        if self.album.image == nil
          get_image = LastFM::Album.get_info(:artist => "#{self.album.artist.name}", :album => "#{self.album.name}")
          self.album.image = get_image["album"]["image"][2]["#text"]
        end
      # LastFM::Album.get_info(:artist => "michael jackson", :album => "ben")
      # tempalbum["album"]["image"][2]["#text"]
      self.album.release = f.tag2["TYER"]
      self.genre = Genre.find_or_create_by_name(f.tag2["TCON"])
      # get all artist apearing on the track and iterate through them(not album artist)
      f.tag2["TPE1"].split("/").each do |i|
        # binding.pry
        # a = []
        # a[0] = Artist.find_or_create_by_name(i)
        # binding.pry
        self.artists << Artist.find_or_create_by_name(i)
        # binding.pry
      end
      user.library.albums << self.album
      user.library.artists << self.artists
      # binding.pry

      # # Attached picture frame
      # cover = tag.frame_list('APIC').first
      # cover.mime_type
      # cover.picture
      # self.parse_artist(data)
      # binding.pry
      end
  end

    def to_jq_upload
      # binding.pry
    {
      "id" => id,
      "name" => title,
      "size" => size * 1024 * 1024,
      "url" => track_location_url,
      "track_url" => self.track_location,
      # "delete_url" => library_track_path(:id => self.id),
      "delete_type" => "DELETE"
    }
  end


  #   def to_jq_upload
  #     binding.pry
  #   {
  #     "name" => read_attribute(:track),
  #     "size" => track.size,
  #     "url" => track.url,
  #     "thumbnail_url" => track.thumb.url,
  #     "delete_url" => track_path(:id => id),
  #     "delete_type" => "DELETE"
  #   }
  # end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_filter :load_library

    def index
      @tracks = current_user.library.tracks
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: TracksDatatable.new(view_context) }
      # format.json { render json: @tracks }
    end
  end



  # def index
  #   respond_to do |format|
  #     format.html
  #     format.json { render json: ProductsDatatable.new(view_context) }
  #   end
  # end



  def new
    # binding.pry
    @track = Track.new
    # @artist = Artist.new
    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @track }
    # end
  end


  def create
    # binding.pry
    p_attr = params[:track]
    p_attr[:file] = params[:track][:track_location].first if params[:track][:track_location].class == Array
      @track = Track.new(p_attr)
      @track.library = @library
      @track.user = current_user
      @track.parse_id3(@track)
      if @track.save
        respond_to do |format|
          format.html {  
            render :json => [@track.to_jq_upload].to_json, 
            :content_type => 'text/html',
            :layout => false
          }
          format.json {  
            render :json => { :files => [@track.to_jq_upload], :status => :done }     
          }
        end
      else 
        render :json => [{:error => "custom_failure"}], :status => 304
      end
    end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    render :json => true
  end
# end

  # def create
  #   # binding.pry
  #   @track = Track.new(params[:track])
  #   # binding.pry
  #   @track.library = @library
  #   @track.user = current_user
  #   @track.parse_id3(@track)
  #   respond_to do |format|
  #     if @track.save
  #       format.json { render json: { :files => [@track.to_jq_upload]}, status: :created }
  #       # format.js do
  #       #   flash[:notice] = "Track was successfully uploaded"
  #       # end
  #       # format.html { redirect_to library_track_path(@library, @track), notice: Track was successfully created. }
  #    #    format.json do
  #    #      render :json => { 
  #    #         :status => :ok, 
  #    #         :message => "Success!",
  #    #         :html => "<b>congrats</b>"
  #    #      }.to_json
  #    # end  
  #       # format.json { render json: @library_track, status: :created, location: @track }
  #     else
  #       format.html { render action: "new" }
  #       # format.json do
  #       #   render json: 'Track was successfully created.'
  #       # end
  #     end
  #   end
  # end

  def show
    @track = Track.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @track }
    end
  end

  # def destroy
  #   # binding.pry
  #   @track = Track.find(params[:id])
  #   @track.destroy

  #   respond_to do |format|
  #     format.html { redirect_to library_tracks_url }
  #     format.json { redirect_to library_tracks_url }
  #   end
  # end

  def update
    @track = Track.new(params[:track])
    @track.libraries << @library
    @track.parse_id3(@track)

    respond_to do |format|
      if @track.save

        format.html { redirect_to library_track_path(@library, @track), notice: 'Track was successfully created.' }
        format.json { render json: @library_track, status: :created, location: @track }
      else
        format.html { render action: "new" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  def land
  end





  protected
  def load_library
    @library = Library.find(current_user.library.id)
  end


end

app/views/tracks/_form.html.erb
<%= form_for(@track, :url => library_tracks_path(current_user.library) , :html => {:multipart => true, :id => "fileupload", :remote => :true}) do |f| %>
<%# binding.pry %>
<div class="form-actions fileupload-buttonbar no-margin">
        
        <span class="btn btn-small fileinput-button">
            <i class="icon-plus"></i>
            <span><%= t('fileupload.add_files') %></span>
            <%= f.file_field :track_location, :multiple => true, name: "track[track_location]" %>
        </span>

        <button type="submit" class="btn btn-primary btn-small start">
            <i class="icon-upload"></i>
            <span><%= t('fileupload.start_upload') %></span>
        </button>

        <button type="reset" class="btn btn-inverse btn-small cancel">
            <i class="icon-ban-circle"></i>
            <span><%= t('fileupload.cancel_upload') %></span>
        </button>

        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
        </tbody>
        </table>
    <% end %>
</div>
<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>

app/views/tracks/_new.html.erb
<!-- <div class="wrap">
    <div class="content container-fluid">
 -->        <div class="row-fluid pull-left">
            <div class="span10">
                <section class="widget">
                    <div class="body">
                        <!-- <form id="fileupload" action="new" method="PUT" enctype="multipart/form-data"> -->
                            <div class="row-fluid">
                                <div class="span12">
                                    <div id="dropzone"  class="dropzone">
                                        Drop files here
                                        <i class="icon-download-alt pull-right"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="span12 fileupload-progress fade">
                                    <!-- The global progress bar -->
                                    <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                                        <div class="bar" style="width:0%;"></div>
                                    </div>
                                    <!-- The extended global progress information -->
                                    <div class="progress-extended">&nbsp;</div>
                                </div>
                            </div>
                            
                              <%= render 'tracks/form' %>
<!--                                 <span class="btn btn-small fileinput-button">
                                        <i class="icon-plus"></i>
                                        <span>Add files...</span>
                                        <input type="file" name="files[]" multiple="">
                                </span> -->
<!--                                 <button type="submit" class="btn btn-primary btn-small start">
                                    <i class="icon-upload"></i>
                                    <span>Start upload</span>
                                </button> -->
<!--                                 <button type="reset" class="btn btn-inverse btn-small cancel">
                                    <i class="icon-ban-circle"></i>
                                    <span>Cancel upload</span>
                                </button> -->
                            
                            <div class="fileupload-loading"><i class="icon-spin icon-spinner"></i></div>
                            <!-- The table listing the files available for upload/download -->
                            <!-- <table role="presentation" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table> -->
                        <!-- </form> -->
                    </div>
                </section>
            </div>
        </div>
<!--     </div>
</div> -->

<%= render "upload" %>

<%= render "download" %>

app/views/tracks/create.js.erb
<% binding.pry %>
$(".progress").text("<%= escape_javascript(flash[:notice]) %>")
$(".progress").show()

app/views/tracks/create.json.erb
<%# binding.pry %>
<%#= escape_javascript(flash[:notice]) %>
// $(".progress").text("<%= escape_javascript(flash[:notice]) %>")
// $(".progress").show()

app/views/tracks/index.html.erb
<!-- <div class="wrap">
  <div class="content container-fluid">
 -->    <div class="row-fluid pull-left">
      <div class="span10">
        <section class="widget">
          <header>
            <h4>
              <i class="icon-file-alt"></i>
              Tracks In Library
            </h4>
          </header>
          <div class="body">
            <blockquote>
              Column sorting, live search, pagination. Built with
              <a href="http://www.datatables.net/" target="_blank">jQuery DataTables</a>
            </blockquote>
            <table id="datatable-table" class="table table-striped" data-source="<%= library_tracks_url(format: "json") %>">
              <thead>
                <tr>
                  <th>Album Artist</th>
                  <th>Title</th>
                  <th>Featured Artist</th>
                  <th>Album</th>
                  <th>Genre</th>
                  <th>Year</th>
                  <th>Length</th>
                  <th>Size(MB)</th>
                  <th>BPM</th>
                  <th>Del</th>
                </tr>
              </thead>              
              <tbody>
              </tbody>
            </table>
          </div>
        </section>
      </div>
    </div>
<!--   </div>
</div> -->

app/views/tracks/land.html.erb
<div class="wrap">
  <div class="content container-fluid">
    <div class="row-fluid">
        <div class="span1">
            <section class="widget large">
                <a href="<%= link_to 'View Artists', artists_path %>">
                <header>
                    <h4>
                        Artists
                    </h4>
                </header>
                <div class="body">

                </div>
                </a>
            </section>
            <section class="widget large">
                <header>
                    <h4>
                        Mixes
                    </h4>
                </header>
                <div class="body">
                </div>
            </section>
        </div>
        <div class="span3">
            <section class="widget large">
                <header>
                    <h4>
                        Tracks
                    </h4>
                </header>
                <div class="body">
                </div>
            </section>
        </div>
        <div class="span1">
            <section class="widget body">
                <header>
                    <h4>
                        Cube1
                    </h4>
                </header>
                <div class="body">
                </div>
            </section>
        </div>
    </div>
  </div>

</div>

app/views/tracks/new.html.erb
<!-- <div class="wrap">
    <div class="content container-fluid">
 -->        <div class="row-fluid pull-left">
            <div class="span10">
                <section class="widget">
                    <div class="body">
                        <!-- <form id="fileupload" action="new" method="PUT" enctype="multipart/form-data"> -->
                            <div class="row-fluid">
                                <div class="span12">
                                    <div id="dropzone"  class="dropzone">
                                        Drop files here
                                        <i class="icon-download-alt pull-right"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="span12 fileupload-progress fade">
                                    <!-- The global progress bar -->
                                    <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                                        <div class="bar" style="width:0%;"></div>
                                    </div>
                                    <!-- The extended global progress information -->
                                    <div class="progress-extended">&nbsp;</div>
                                </div>
                            </div>
                            
                              <%= render 'form' %>
<!--                                 <span class="btn btn-small fileinput-button">
                                        <i class="icon-plus"></i>
                                        <span>Add files...</span>
                                        <input type="file" name="files[]" multiple="">
                                </span> -->
<!--                                 <button type="submit" class="btn btn-primary btn-small start">
                                    <i class="icon-upload"></i>
                                    <span>Start upload</span>
                                </button> -->
<!--                                 <button type="reset" class="btn btn-inverse btn-small cancel">
                                    <i class="icon-ban-circle"></i>
                                    <span>Cancel upload</span>
                                </button> -->
                            
                            <div class="fileupload-loading"><i class="icon-spin icon-spinner"></i></div>
                            <!-- The table listing the files available for upload/download -->
                            <!-- <table role="presentation" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table> -->
                        <!-- </form> -->
                    </div>
                </section>
            </div>
        </div>
<!--     </div>
</div> -->

<%= render "upload" %>

<%= render "download" %>

app/views/tracks/new.js.erb
// $(".modal-body").html("<%= escape_javascript(render(:partial => 'new')) %>");

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @track.title %>
</p>

<p>
  <b>Track path:</b>
  <%= @track.track_location %>
</p>

<div class="ui-widget">
  <label for="tags">Search Friends: </label>
  <input id="tags" />
</div>

<%= link_to 'Edit', edit_library_track_path(@track) %> |
<%= link_to 'Back', library_tracks_path %>