config/routes.rb
MusicV20::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

  devise_for :users

  root :to => 'home#index'

   resources :artists do
    member do
      get 'albums'
    end
  end
   resources :albums
 
   resources :users
     resources :libraries do
       resources :playlists do
         resources :comments
       end
    resources :tracks do
    end
   end

   resources :friendships do
     collection do
       get :accept, :decline, :cancel, :delete
     end
     member do
       get :friend_request
     end
   end

  match '/search' => 'search#search', :as => 'search'

  match '/libraries/:id/land' => 'tracks#land', :as => 'land'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :age, :artist_type, :birthday, :first_name, :gender, :last_name, :biography, :name, :artist_images_attributes

  has_many :tracks, :through => :artist_tracks
  has_many :artist_tracks
  has_many :albums
  has_many :artist_images
  has_many :libraries, :through => :artist_libraries
  has_many :artist_libraries

  accepts_nested_attributes_for :artist_images, allow_destroy: true

  
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    # @artists = current_user.library.lib_filter(params[:controller])
    @artists = current_user.library.artists
    @artists.uniq!
    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @artists }
    end
  end

  def show
    @artist = Artist.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render json: @artist }
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update_attributes(params[:artist])
      redirect_to @artist, notice: "Successfully updated Artist."
    else
      render :edit
    end
  end

  def albums
    @artist = Artist.find(params[:id])
    respond_to do |format|
      # format.html # show.html.erb
      format.js
    # binding.pry
    end
  end

  def new
    binding.pry
  end

  
end

app/views/artists/_albums.html.erb
<%#= javascript_include_tag "albums" %>
<%# binding.pry %>
<!-- <div class="wrap"> -->
<% @artist.albums.each do |album| %>
  <%= render :partial => 'albums/show', :locals => {:album => album} %>
  <hr>
<% end %>
<%#= render :partial => 'albums/show', :locals => {:artist => @artist, :album => album} %>
    

app/views/artists/_artist.html.erb
<% instance_variable_get("@#{params[:controller]}").each do |a| %>
<%# binding.pry %>
  <li class="span2">
    <% if instance_variable_get("@#{params[:controller]}") == @artists %>
    <a href='<%= artist_path(a.id) %>'>
      <div class="thumbnail">
        <% if a.artist_images.empty? %>
          <img src="img/10.jpg" alt="">          
          <% else %>
          <img src="<%= a.artist_images.first.image %>" alt="">
          <% end %>
          <!-- <div class="caption"> -->
              <h6><%= a.name %></h6>
        </a>
          <!-- </div> -->
      </div>
      <% else %>
        <a href="<%= album_path(a.id) %>">
          <div class="thumbnail">
              <img src="<%= a.image %>" alt="">
            </a>

               <div id="glass_wrapper">
                <span class="glass">
                  <div class="btn-group pull-right" data-id="<%= a.id%>" data-url="">
                    <a id="add_album" class="btn btn-mini icon-plus"></a>
                    <a class="btn btn-mini icon-wrench" href='<%= edit_album_path(a.id) %>'></a>
                  </div>
                  <div class="pull-left" data-id="<%= a.id%>" data-url="">
                    <a id="play_album" class="btn btn-mini icon-play-circle"></a>
                  </div>
                </span>
              </div>
              <!-- <div class="caption"> -->
                  <h6><%= a.name %></h6>
              <!-- </div> -->
          </div>
      <% end %>
    </a>
  </li>
<% end %>

app/views/artists/_artist_image.html.erb
<fieldset>
  <%#= f.label :image, "Image" %>
  <%= f.text_field :image, :class => 'span8' %>
  <%= f.hidden_field :_destroy %>
  <%#= link_to "remove", '#', class: "remove_fields" %>
  <%= link_to '<button type="button" class="btn btn-danger"><i class="icon-trash"></i></button>'.html_safe, '#', class: "remove_fields" %>
</fieldset>

app/views/artists/_bio.html.erb
<%# binding.pry %>
<%= @artist.biography %>

app/views/artists/_form.html.erb
<!-- <div class="wrap"> -->
<!-- <div class="content container-fluid"> -->
    <!-- <div class="row-fluid"> -->
        <!-- <div class="span8"> -->
            <h2 class="page-title">Edit Artist <small>Form To Update Artists Attributes</small></h2>
        <!-- </div> -->
    <!-- </div> -->
    <div class="row-fluid">
        <div class="span6">
            <section class="widget">
<!--                 <header>
                    <h4><i class="icon-user"></i> Account Profile <small>Create new or edit existing user</small></h4>
                </header> -->
                <div class="body">
                    <!-- <form id="user-form" class="form-horizontal label-left"
                          novalidate="novalidate"
                          method="put"
                          data-validate="parsley"> -->

                  <div id="droppable" class="row-fluid">
                    <div class="span4">
                      <div class="text-align-center">
                        <% if @artist.artist_images.empty? %>
                          <img src="img/10.jpg" alt="">          
                            <% else %>
                              <img src="<%= @artist.artist_images.first.image %>" alt="64x64" style="height: 112px;">
                            <% end %>                            
                           </div>
                          </div>
           
                        </div>
        
                        <fieldset>
                        <%= form_for(@artist) do |f| %>
                          <% if @artist.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

                              <ul>
                              <% @artist.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                              <% end %>
                              </ul>
                            </div>
                          <% end %>
                            <legend class="section">Artist Info</legend>
                            <div class="control-group">
                                <label class="control-label" for="prefix">Artist Images</label>
                                <div class="controls controls-row">
                                  <div class="field">
                                    <%= f.fields_for :artist_images do |builder| %>
                                      <%= render 'artist_image', f: builder %>
                                    <% end %>
                                    <%= link_to_add_fields '<button type="button" class="btn btn-success"><i class="icon-plus"></i></button>'.html_safe, f, :artist_images %>
                                  </div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="description" class="control-label">Type of Artist</label>
                                <div class="controls">
                                  <%= select :artist_type, :linkaddress, [["Person","person"],["Group", "group"]] %>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="description" class="control-label">Type of Artist</label>
                                <div class="controls">
                                  <%= select :gender, :linkaddress, [["Male","male"],["Female", "female"]] %>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="stage-name">Stage Name</label>
                                <div class="controls controls-row">
                                      <%= f.text_field :name, :class => 'span8', :id => 'Name' %><!-- <button id="go" class="btn btn-primary"> Get Images </button> -->
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="first-name">First Name<span class="required">*</span></label>
                                <div class="controls controls-row">
                                  <%#= f.label :first_name %>
                                  <%= f.text_field :first_name, :class => 'span4', :id => 'First Name' %>
                                <!-- <label class="control-label" for="last-name">Last Name<span class="required">*</span></label> -->
                                  <%#= f.label :last_name %>
                                  <%= f.text_field :last_name, :class => 'span4', :id => 'Last Name'  %>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="biography">Biography<span class="required">*</span></label>
                                <div class="controls controls-row">
                                  <%= f.text_area :biography, :class => 'span10', :id => 'Last Name'  %>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="exp" class="control-label">Account expiration date</label>
                                <div class="controls">
                                    <input id="exp" class="input-block-level datepicker" type="text" name="exp" value="">
                                    <span class="help-block">Bootstrap datepicker</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="description" class="control-label">Birthday</label>
                                <div class="controls">
                                  <%= f.date_select :birthday, :class => 'input-block-level date-picker', :id => 'Birthday' %>
                                </div>
                            </div>

                        </fieldset>

                        <div class="form-actions ">
                            <!-- <button type="submit" class="btn btn-primary">Validate &amp; Submit</button> -->
                            <%= f.submit "Validate & Submit", :class => 'btn btn-primary offset3'%>
                            <button type="button" class="btn">Cancel</button>
                        </div>

                        <% end %>

                    <!-- </form> -->
                </div>
            </section>
        </div>

        <div id="results" class="span5" style="z-index:200">
          <!-- <div> -->
              <!-- <input id="artist" type="text" placeholder="Enter artist name ..." </input> -->
              <button id="go" class="btn btn-primary"> Get Images </button>
          <!-- </div> -->
          <!-- <section class="widget tiny"><div class="body"><div id="results"></div></div></section> -->
        </div>

    </div>
<!-- </div>
</div> -->


<script>
 $('.datepicker').datepicker({
     format: 'mm-dd-yyyy'
 });
</script>

app/views/artists/_images.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artist Images</title>
     <style>
        .image-container {
            width: 240px;
            height: 240px;
            background-size: cover;
            background-image:"http://i.stack.imgur.com/2OrtT.jpg";
            background-repeat: no-repeat;
            background-position: 50% 50%;
            float:left;
        }
     </style>
  </head>

<body>

<div id="wrap" class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
        <a id='show-search' class="brand">Artist Images</a>
        <ul class="nav">
          <li class="nav-choice active"><a id='show-main'>Main</a></li>
          <li class="nav-choice"><a href="https://github.com/plamere/en-demos/blob/master/images/images.html">The Source</a></li>
          <li class="nav-choice"><a href="http://developer.echonest.com/docs/v4/artist.html#images">Images API</a></li>
        </ul>
        <ul class="nav pull-right">
          <li class="nav-choice"><a href="http://static.echonest.com/labs">Labs</a></li>
          <li class="nav-choice"><a href="http://static.echonest.com/labs/demo.html">Demos</a></li>
          <li class="nav-choice"><a href="http://developer.echonest.com">developer.echonest.com</a></li>
        </ul>
    </div>
  </div>
</div>

<div class="container">
    <div class="well offset1 span9" >
        <h2> Artist Images </h2>
        <p> A demonstration of how to use The Echo Nest API to get images of an artist</p>
            <div>
                <input id="artist" type="text" placeholder="Enter artist name ..." </input>
                <button id="go" class="btn btn-primary"> Get Images </button>
            </div>
            <div id="info" class=""> </div>
    </div>
</div>

<div id="results"> </div>

<script type="text/javascript">

jQuery.ajaxSettings.traditional = true; 
var apiKey = 'UJ6VUETJ7VUYJAFHB';

function fetchImages(artist) {
    var url = 'http://developer.echonest.com/api/v4/artist/images';

    var args = { 
            format:'json', 
            api_key: apiKey,
            name: artist,
            results: 100, 
    }; 

    info("Fetching images for " + artist);
    $.getJSON(url, args,
            function(data) {
                $("#results").empty();
                if (! ('images' in data.response)) {
                    error("Can't find any images for " + artist);
                } else {
                    $("#results").show();
                    $.each(data.response.images, function(index, item) {
                        var div = formatItem(index, item);
                        $("#results").append(div);
                    });
                    info("Showing " + data.response.images.length + " of " + data.response.total + " images for " + artist);
                }
            },
            function() {
                error("Trouble getting blog posts for " + artist);
            }
        );
}

function formatItem(which, item) {
    var img = $("<div>");
    img.addClass("image-container span3");
    img.css("background-image", "url(" +item.url + ")");

    var attribution = $("<span class='label'>")
        .text(item.license.attribution)
        .hide();

    img.append(attribution);
    img.hover( 
        function(evt) {
            img.find('.label').show();
        },
        function(evt) {
            img.find('.label').hide();
        }
    );
    return img;
}


function go() {
    var artist = $.trim($("#artist").val());
    if (artist.length  > 0) {
        fetchImages(artist);
    } else {
        info("Type an artist name first");
    }
}

function info(s) {
    $("#info").removeClass();
    if (s.length > 0) {
        $("#info").addClass("alert alert-info");
    }
    $("#info").text(s);
}

function error(s) {
    $("#info").removeClass();
    if (s.length > 0) {
        $("#info").addClass("alert alert-error");
    }
    $("#info").text(s);
}
    
$(document).ready(function() {
    // fetchApiKey will fetch the Echo Nest demo key for demos
    // hosted on The Echo Nest, otherwise it fetch an empty key
    fetchApiKey( function(api_key, isLoggedIn) {
        if (!api_key) {
            api_key = 'MY_ECHO_NEST_API_KEY';
        }
        apiKey = api_key;
        $("#go").click(go);
        $("#artist").change(go);
    });
});

</script>
</body>
</html>

app/views/artists/_show.html.erb
_show.html.erb

app/views/artists/albums.js.erb
// $("#Albums").html("<%= escape_javascript(render(:partial => 'albums')) %>").hide().fadeIn(3000);
$("#Albums").html("<%= escape_javascript(render :partial => 'albums') %>").fadeIn('slow');
<%#= javascript_include_tag "albums" %>

app/views/artists/bio.js.erb
// $('.tab-pane').empty()
$("#Biography").fadeIn('slow', "<%= escape_javascript(render(:partial => 'bio')) %>");

app/views/artists/edit.html.erb
<%= render "form" %>

app/views/artists/index.html.erb
<!-- <div class="wrap"> -->
  <!-- <div class="content container-fluid"> -->
    <!-- <div class="row-fluid"> -->
        <!-- <div class="span10"> -->
            <h2 class="page-title" >Artists <small>In Your Library</small></h2>
        <!-- </div> -->
    <!-- </div> -->
    <div class="row-fluid">
      <div class="span9">
        <!-- <section class="widget"> -->
<!--           <header>
              <h4>
                  <i class="icon-music"></i>
                  Artists
                  <small>In Your Library</small>
              </h4>
          </header> -->
          <div class="body">
              <ul class="thumbnails">
                  <%= render :partial => 'artist' %>
              </ul>
          </div>
        <!-- </section> -->
      </div>
    </div>
<!--   </div>
</div> -->

app/views/artists/show.html.erb
<%# binding.pry %>
<%#= javascript_include_tag "albums" %>
<!-- <div class="wrap"> -->
<!-- <div class="content container-fluid"> -->
    <!-- <div class="row-fluid hidden-print"> -->
        <!-- <div class="span12"> -->
            
        <!-- </div> -->
    <!-- </div> -->
    <div class="row-fluid pull-left">
        <div class="span10">
            <!-- <section class="widget"> -->
                <div class="body no-margin">
                  <div id="myCarousel" class="carousel slide">
                    <ol class="carousel-indicators">
                      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                      <li data-target="#myCarousel" data-slide-to="1"></li>
                      <li data-target="#myCarousel" data-slide-to="2"></li>
                    </ol>
                    <!-- Carousel items -->
                    <div class="carousel-inner">
                      <div class="active item">
                          <a href="/users/sign_up"><img src="<%= image_path('music-music-dj-wallpaper.jpg') %>"> </a>
                        </div>
                        <div class="item">
                          <a href="/users/sign_up"><img src="<%= image_path('02.jpg') %>"> </a>
                        </div>
                        <div class="item">
                          <a href="/users/sign_up"><img src="<%= image_path('03.jpg') %>"> </a>
                        </div>
                    </div>
                    <!-- Carousel nav -->
                    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
                  </div>
                  <h2 class="page-title" ><%= @artist.name %> </h2>
                    <hr>
                    <a id="album_options" class="icon-wrench" href='<%= edit_artist_path(@artist.id) %>'></a>
    <div class="row-fluid">
      <div id="artist_tabs" class="span12">
        <section class="widget widget-tabs">
          <header>
            <ul class="nav nav-tabs offset4">
              <li class="active"><%= link_to "Albums", albums_artist_path, 'data-toggle' => 'tab', :remote => true %></li>
              <li><%= link_to "Biography", artist_path(@artist), 'data-toggle' => 'tab', :remote => true %></li>
              <li>
                <a href="mixes" data-toggle="tab">Mixes</a>
              </li>
              <li>
                <a href="BTM" data-toggle="tab">BTM (Behind The Music)</a>
              </li>
            </ul>
          </header>
          <div class="body tab-content">
            <div id="Albums" class="tab-pane active clearfix"></div>
            <div id="Biography" class="tab-pane"></div>
            <div id="BTM" class="tab-pane"></div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>
</div>
<!-- </div> -->


<script type="text/javascript">
  $.ajax({
      type: "GET",
      url: location.href + "/albums",
      cache: false,
      success: function(data){
        // $("#Albums").append(html);
      }
  });
</script>

app/views/artists/show.js.erb
<%# binding.pry %>
$("#Biography").html("<%= escape_javascript(render(:partial => 'bio')) %>").fadeIn(3000);