config/routes.rb
MusicV20::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

  devise_for :users

  root :to => 'home#index'

   resources :artists do
    member do
      get 'albums'
    end
  end
   resources :albums
 
   resources :users
     resources :libraries do
       resources :playlists do
         resources :comments
       end
    resources :tracks do
    end
   end

   resources :friendships do
     collection do
       get :accept, :decline, :cancel, :delete
     end
     member do
       get :friend_request
     end
   end

  match '/search' => 'search#search', :as => 'search'

  match '/libraries/:id/land' => 'tracks#land', :as => 'land'

end

app/views/home/_guestsidebar.html.erb
<nav id="sidebar" class="sidebar nav-collapse collapse">
  <ul id="side-nav" class="side-nav">
    <li class="accordion-group">
      <a class="accordion-toggle collapsed" data-toggle="collapse"
         data-parent="#side-nav" href="#special-collapse"><i class="icon-user"></i> <span class="name">Login / Register</span></a>
      <ul id="special-collapse" class="accordion-body collapse">
        <li><a href="/users/sign_up">Register</a></li>
        <li><a href="<%= new_user_session_path %>">Login</a></li>
      </ul>
    </li>
    <li class="visible-phone">
      <a href="<%= new_user_session_path %>"><i class="icon-signout"></i> <span class="name">Sign Out</span></a>
    </li>
  </ul>
</nav>

app/views/home/_modal.html.erb
<!-- <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog"> -->
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" >×</button>
    <h4 id="myModalLabel">Upload Music</h4>
  </div>
  <div class="modal-body">
    <h5>Upload Form Comming Soon!!!</h5>
    <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem.</p>

    <h5>Popover in a modal</h5>
    <p>This <a href="#" role="button" class="btn popover-test btn-small" title=""
     data-content="And here's some amazing content. It's very engaging. right?"
     data-original-title="A Title">button</a> should trigger a popover on click.</p>

     <h5>Tooltips in a modal</h5>
     <p><a href="#" class="tooltip-test" title="" data-original-title="Tooltip">This link</a> and <a href="#" class="tooltip-test" title="" data-original-title="Tooltip">that link</a> should have tooltips on hover.</p>

     <hr>

     <h5>Overflowing text to show optional scrollbar</h5>
     <p>We set a fixed <code>max-height</code> on the <code>.modal-body</code>. Watch it overflow with all this extra lorem ipsum text we've included.</p>
     <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
     <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
     <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
     <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
     <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
     <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
   </div>
   <div class="modal-footer">
    <button class="btn" data-dismiss="modal">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
<!-- </div> -->

app/views/home/_player.html.erb
<%#= javascript_include_tag "albums" %>

<div class="audio-player">
  <!-- <section > -->
    <header>
      <h4>
        <!-- <i class="icon-list"></i> -->
        Main Player
      </h4>
    </header>
    <div class="body">
      <div class="audio-control prev_track"></div>
      <div class="audio-control play"></div>
      <div class="audio-control next_track"></div>
    </div>
    <div id="graphPixels">
      <div></div>
    </div> 

  <!-- </section> -->
</div>

app/views/home/_playlist.html.erb
<!-- <div style="z-index: 1000">
  <div id="plspan" class="span5">
    <section class="playlist">
      <header>
        <h4>
          <i class="icon-list"></i>
          PlayList
        </h4>
        <div>
          <a id="slideleft" class="btn btn-mini icon-arrow-right pull-right"></a>
        </div>
      </header>
      <div class="slide">        
        <ul class="playlistSongs">

        </ul>
      </div>
      <div>
        <a class="btn btn-mini icon-save pull-bottom"></a>
      </div>
    </section>
  </div>
</div> -->

<!-- <div class="content container-fluid" > -->
  <!-- <div class="row-fluid"> -->
<!-- <div class="span2"> -->
  <section id="plspan" class="music_glass" >
<!--     <header>
      <h4>
        <i class="icon-list"></i>
        Playlist
      </h4>
      <div class="actions">
        <button id="slideright" class="btn btn-transparent btn-mini icon-arrow-right"></button>
      </div>
    </header> -->
      <div id="playerTop">
        <div id="trackArt"></div>
        <div id="trackArtist"></div>
        <div id="trackTitle"></div>
        
      </div>
      <div id="seekDiv">
        <div id="trackProgress"></div>
        <div id="mainProgress">
          <div class="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" style="width: 0%;"></div>
          <a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 0%;"></a>
        </div>
        <div id="trackDuration"></div>
      </div>
      <div id="playerControls">
        <div id="trackRepeat"></div>
        <div id="trackShuffle"></div>
        <div id="prevTrack"></div>
        <div id="playTrack" class="play_pause playTrack"></div>
        <div id="nextTrack"></div>
        
        <div id="volumeSlider">
          <div class="volumeTooltip"></div>
        </div>
        <div class="volumeIcon"></div>    
      </div>
    <!-- *************************************************************** -->
<!--     <div class="body">
      <div id="feed" class="feed">
        <div class="wrapper">
          <div class="vertical-line"></div>
          <section class="feed-item">
            <div class="text">
              <ul id="Playlist" class="playlistSongs">
                <li class="pl_tracks "><span class="icon-caret-right ">&nbsp;</span> Test track</li>

              </ul>              
            </div>

          </section>
          
        </div>
      </div>
    </div> -->
        <div style="position:relative">
<!--         <div id="graphPixels">
          <div></div>
        </div>  -->
          <!-- <i id="plOptions" class="icon-caret-right icon-large"></i> -->
            <span class="plControl" style="position:absolute">
              <i class="icon-save icon-large"></i>
              <i class="icon-plus-sign-alt icon-large"></i>
              <i class="icon-share icon-large"></i>
              <i class="icon-trash  pull-right icon-large"></i>
              <i class="icon-remove-circle pull-right icon-large"></i>            
            </span>
<!--             <div class="plSave">
                <input type="text" id="normal-field" class="span2" placeholder="Save Playlist As...">
                <div class="input-group-btn">
                    <button type="button" class="btn btn-success"><i class="fa fa-refresh"></i></button>
                </div>
            </div> -->

<!--             <div class="form-group">
                <label for="bar">Whole bar appended</label>

                <div class="input-group">
                    <input type="text" class="span2" >
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-success"><i class="fa fa-refresh"></i></button>
                    </div>
                </div>

            </div> -->
<!--             <span class="plSave" >
              <input type="text" id="normal-field" class="span2" placeholder="Save Playlist As..." ><i class="icon-check"></i>
            </span> -->
<!--           <div>
            <input type="text" id="normal-field" class="span2" placeholder="Save Playlist As..." >
          </div> -->
        </div>
  </section>
<!-- </div> -->
<!-- </div> -->
<!-- </div> -->

app/views/home/_sidebar.html.erb
<nav id="sidebar" class="sidebar nav-collapse collapse">
  <ul id="side-nav" class="side-nav">
    <li class="active accordion-group">
      <a class="accordion-toggle" data-toggle="collapse"
         data-parent="#side-nav" href="#forms-collapse"><i class="icon-headphones"></i> <span class="name">My Music</span></a>
      <ul id="forms-collapse" class="accordion-body collapse in">
        <% if current_user.library == nil %>
        <li><a href="<%= new_library_path %>">Artists</a></li>
        <li><a href="<%= new_library_path %>">Albums</a></li>
        <li><a href="<%= new_library_path %>">Mixes</a></li>
        <li><a href="<%= new_library_path %>">Tracks</a></li>
        <li><a href="<%= new_library_path %>">Upload Music</a></li>
        <% else %>
        <li><a href="<%= artists_path %>">Artists</a></li>
        <li><a href="<%= albums_path %>">Albums</a></li>
        <li><a href="<%= library_playlists_path(current_user.library) %>">Mixes</a></li>
        <li><a href="<%= library_tracks_path(current_user.id) %>">Tracks</a></li>
        <li><a href="<%= new_library_track_path(current_user.library) %>">Upload Music</a></li>
        <% end %>
      </ul>
    </li>
    <li class="accordion-group">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#side-nav" href="#stats-collapse"><i class="icon-group"></i> <span class="name">Friends</span></a>
      <ul id="stats-collapse" class="accordion-body collapse">
        <li><a href="#">Invite</a></li>
        <li><a href="#">Communicate</a></li>
        <li><a href="#">Manage</a></li>
      </ul>
    </li>
    <li class="accordion-group">
      <a class="accordion-toggle collapsed" data-toggle="collapse"
         data-parent="#side-nav" href="#ui-collapse"><i class="icon-magic"></i> <span class="name">User Interface</span></a>
      <ul id="ui-collapse" class="accordion-body collapse">
        <li><a href="ui_buttons.html">Buttons</a></li>
        <li><a href="ui_dialogs.html">Dialogs</a></li>
        <li><a href="ui_icons.html">Icons</a></li>
        <li><a href="ui_tabs.html">Tabs</a></li>
        <li><a href="ui_accordion.html">Accordion</a></li>
      </ul>
    </li>
    <li class="accordion-group">
      <a class="accordion-toggle collapsed" data-toggle="collapse"
         data-parent="#side-nav" href="#components-collapse"><i class="icon-bookmark-empty"></i> <span class="name">Components</span></a>
      <ul id="components-collapse" class="accordion-body collapse">
        <li><a href="component_calendar.html">Calendar</a></li>
        <li><a href="component_maps.html">Maps</a></li>
        <li><a href="component_gallery.html">Gallery</a></li>
        <li><a href="component_fileupload.html">Fileupload</a></li>
      </ul>
    </li>
    <li class="accordion-group">
      <a class="accordion-toggle collapsed" data-toggle="collapse"
         data-parent="#side-nav" href="#tables-collapse"><i class="icon-table"></i> <span class="name">Tables</span></a>
      <ul id="tables-collapse" class="accordion-body collapse">
        <li><a href="tables_static.html">Static</a></li>
        <li><a href="tables_dynamic.html">Dynamic</a></li>
      </ul>
    </li>
    <li >
      <%= link_to '<i class="icon-signout"></i><span class="name">Sign Out</span>'.html_safe, destroy_user_session_path, :method => :delete %>
    </li>
  </ul>
  <div id="sidebar-settings" class="settings">
    <button type="button" data-value="icons" class="btn-icons btn btn-transparent btn-small">Icons</button>
    <button type="button" data-value="auto" class="btn-auto btn btn-transparent btn-small">Auto</button>
  </div>
</nav>

<script type="text/template" id="sidebar-settings-template">
        {{ auto = sidebarState == 'auto'}}
        {{ if (auto) {}}
            <button type="button"
                    data-value="icons"
                    class="btn-icons btn btn-transparent btn-small">Icons</button>
    <button type="button"
            data-value="auto"
            class="btn-auto btn btn-transparent btn-small">Auto</button>
        {{} else {}}
            <button type="button"
                    data-value="auto"
                    class="btn btn-transparent btn-small">Auto</button>
        {{ } }}
</script>

app/views/home/_topnav.html.erb
<!-- <div class="wrap"> -->
    <p class="notice"><%= notice %></p>
    <header class="page-header">
        <div class="navbar">
            <div class="navbar-inner">
                <ul class="nav pull-right">

                    <li class="dropdown">
                        <a href="#" title="Messages" id="messages"
                           class="dropdown-toggle"
                           data-toggle="modal" data-target="#myModal">
                            <i class="icon-cloud-upload"></i>
                        </a>
<!--                         <ul id="messages-menu" class="dropdown-menu messages" role="menu">
                            <li role="presentation">
                                <a href="#" class="message">
                                    <img src="img/1.jpg" alt="">
                                    <div class="details">
                                        <div class="sender">Jane Hew</div>
                                        <div class="text">
                                            Hey, John! How is it going? ...
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="message">
                                    <img src="img/2.jpg" alt="">
                                    <div class="details">
                                        <div class="sender">Alies Rumiancaŭ</div>
                                        <div class="text">
                                            I'll definitely buy this template
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="message">
                                    <img src="img/3.jpg" alt="">
                                    <div class="details">
                                        <div class="sender">Michał Rumiancaŭ</div>
                                        <div class="text">
                                            Is it really Lore ipsum? Lore ...
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="text-align-center see-all">
                                    See all messages <i class="icon-arrow-right"></i>
                                </a>
                            </li>
                        </ul> -->
                    </li>

                    <li class="dropdown">
                        <a href="#" title="Messages" id="messages"
                           class="dropdown-toggle"
                           data-toggle="dropdown">
                            <i class="icon-comments"></i>
                        </a>
                        <ul id="messages-menu" class="dropdown-menu messages" role="menu">
                            <li role="presentation">
                                <a href="#" class="message">
                                    <img src="/assets/1.jpg" alt="">
                                    <div class="details">
                                        <div class="sender">Jane Hew</div>
                                        <div class="text">
                                            Hey, John! How is it going? ...
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="message">
                                    <img src="/assets/2.jpg" alt="">
                                    <div class="details">
                                        <div class="sender">Alies Rumiancaŭ</div>
                                        <div class="text">
                                            I'll definitely buy this template
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="message">
                                    <img src="/assets/3.jpg" alt="">
                                    <div class="details">
                                        <div class="sender">Michał Rumiancaŭ</div>
                                        <div class="text">
                                            Is it really Lore ipsum? Lore ...
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="text-align-center see-all">
                                    See all messages <i class="icon-arrow-right"></i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" title="8 support tickets"
                           class="dropdown-toggle"
                           data-toggle="dropdown">
                            <i class="icon-group"></i>
                            <span class="count">8</span>
                        </a>
                        <ul id="support-menu" class="dropdown-menu support" role="menu">
                            <li role="presentation">
                                <a href="#" class="support-ticket">
                                    <div class="picture">
                                        <span class="label label-important"><i class="icon-bell-alt"></i></span>
                                    </div>
                                    <div class="details">
                                        Check out this awesome ticket
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="support-ticket">
                                    <div class="picture">
                                        <span class="label label-warning"><i class="icon-question-sign"></i></span>
                                    </div>
                                    <div class="details">
                                        "What is the best way to get ...
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="support-ticket">
                                    <div class="picture">
                                        <span class="label label-success"><i class="icon-tag"></i></span>
                                    </div>
                                    <div class="details">
                                        This is just a simple notification
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="support-ticket">
                                    <div class="picture">
                                        <span class="label label-info"><i class="icon-info-sign"></i></span>
                                    </div>
                                    <div class="details">
                                        12 new orders has arrived today
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="support-ticket">
                                    <div class="picture">
                                        <span class="label label-important"><i class="icon-plus"></i></span>
                                    </div>
                                    <div class="details">
                                        One more thing that just happened
                                    </div>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="text-align-center see-all">
                                    See all tickets <i class="icon-arrow-right"></i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="divider"></li>
                    <li class="hidden-phone">
                        <a href="#" id="settings"
                           data-toggle="popover"
                           data-placement="bottom"
                           title="">
                            <i class="icon-cog"></i>
                        </a>
                    </li>
                    <li class="hidden-phone dropdown">
                        <a href="#" title="Account" id="account"
                           class="dropdown-toggle"
                           data-toggle="dropdown">
                            <i class="icon-user"></i>
                        </a>
                        <ul id="account-menu" class="dropdown-menu account" role="menu">
                            <li role="presentation" class="account-picture">
                                <img src="/assets/2.jpg" alt="">
                                Philip Daineka
                            </li>
                            <li role="presentation">
                                <a href="form_account.html" class="link">
                                    <i class="icon-user"></i>
                                    Profile
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="component_calendar.html" class="link">
                                    <i class="icon-calendar"></i>
                                    Calendar
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#" class="link">
                                    <i class="icon-inbox"></i>
                                    Inbox
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="visible-phone">
                        <a href="#"
                           class="btn-navbar"
                           data-toggle="collapse"
                           data-target=".sidebar"
                           title="">
                            <i class="icon-reorder"></i>
                        </a>
                    </li>
                    <li class="hidden-phone"><a href="<%= new_user_session_path %>"><i class="icon-signout"></i></a></li>
                </ul>
                <form class="navbar-search pull-right">
                    <input type="search" class="search-query" placeholder="Search...">
                    <%#= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                </form>
            </div>
        </div>

    </header>
<!-- </div> -->

<script type="text/template" id="settings-template">
    <div class="setting clearfix">
        <div>Background</div>
        <div id="background-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
            {{ dark = background == 'dark'; light = background == 'light';}}
            <button type="button" data-value="dark" class="btn btn-small btn-transparent {{= dark? 'active' : '' }}">Dark</button>
            <button type="button" data-value="light" class="btn btn-small btn-transparent {{= light? 'active' : '' }}">Light</button>
        </div>
    </div>
    <div class="setting clearfix">
        <div>Sidebar on the</div>
        <div id="sidebar-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
            {{ onRight = sidebar == 'right'}}
            <button type="button" data-value="left" class="btn btn-small btn-transparent {{= onRight? '' : 'active' }}">Left</button>
            <button type="button" data-value="right" class="btn btn-small btn-transparent {{= onRight? 'active' : '' }}">Right</button>
        </div>
    </div>
    <div class="setting clearfix">
        <div>Sidebar</div>
        <div id="display-sidebar-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
            {{ display = displaySidebar}}
            <button type="button" data-value="true" class="btn btn-small btn-transparent {{= display? 'active' : '' }}">Show</button>
            <button type="button" data-value="false" class="btn btn-small btn-transparent {{= display? '' : 'active' }}">Hide</button>
        </div>
    </div>
</script>