config/routes.rb
MusicV20::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

  devise_for :users

  root :to => 'home#index'

   resources :artists do
    member do
      get 'albums'
    end
  end
   resources :albums
 
   resources :users
     resources :libraries do
       resources :playlists do
         resources :comments
       end
    resources :tracks do
    end
   end

   resources :friendships do
     collection do
       get :accept, :decline, :cancel, :delete
     end
     member do
       get :friend_request
     end
   end

  match '/search' => 'search#search', :as => 'search'

  match '/libraries/:id/land' => 'tracks#land', :as => 'land'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  attr_accessible :library_id, :name, :private, :track_position, :user_id

  has_many :comments, as: :commentable
  has_many :tracks, :through => :playlist_tracks
  has_many :playlist_tracks
  has_many :users, :through => :user_playlists
  has_many :user_playlists
  has_many :libraries, :through => :library_playlists
  has_many :library_playlists

  accepts_nested_attributes_for :tracks
  accepts_nested_attributes_for :playlist_tracks

  letsrate_rateable "rating"


  def get_tracks(data)
    # binding.pry
    self.name = data[:name]
    data[:tracks].each do |t|
      self.tracks << Track.find_by_id(t)
    end
  end
  
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

    before_filter :load_library

    def index
      @playlists = current_user.library.playlists
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @playlists }
      end
    end

    def new
      binding.pry
      @playlist = Playlist.new

      # binding.pry
      # @tracks = current_user.library.tracks
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @playlist }
      end
    end

    def show
      @library = Library.find(params[:library_id])
      @playlist = Playlist.find(params[:id])
      @commentable = @playlist
      @comments = @commentable.comments
      @comment = Comment.new

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @playlist }
      end
    end

    def edit
      # binding.pry
    end

    def create
      # binding.pry
      @playlist = Playlist.new(params[:playlist])
      @playlist.libraries << @library
      @playlist.get_tracks(params)
      # binding.pry
      respond_to do |format|
        if @playlist.save
            format.html 
            format.js
        else
          format.html { render action: "new" }
          format.json { render json: @playlist.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @playlist = Playlist.find(params[:id])
      @playlist.destroy

      respond_to do |format|
        format.html { redirect_to library_playlists_url }
        format.json { head :no_content }

    end
  end
    def update
      @playlist = Playlist.find(params[:id])
      @playlist.save
      #binding.pry
      redirect_to library_playlist_path(@playlist)

    end



    protected
    def load_library
      @library = Library.find(params[:library_id])
      @tracks = current_user.library.tracks
    end

    
end

app/views/playlists/_tracks.html.erb
<div id="droppable">
  <h1 class="ui-widget-header">Playlist</h1>
  <div class="ui-widget-content">
    <ol>
      <li class="placeholder">Drag your music here</li>
    </ol>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Track #</th>
      <th>Album Artist</th>
      <th>Title</th>
      <th>Featured Artist</th>
      <th>Album</th>
      <th>Year</th>
      <th>Genre</th>
      <th>Length</th>
      <th>Size</th>
      <th>BPM</th>
      <th>Ratings</th>
      <th width ="20px"> </th>

    </tr>
</thead>

   <% @tracks.each do |track| %>
   <tbody id="tdrop">
    <tr class="tr_row">
      <td><%= track.track_number %></td>
      <td><%= track.album.artist.name %></td>
      <td><%= track.title %></td>
      <td><%= track.artists.map{ |a| [a][0].name }.join(", ") %></td>
      <td><%= track.album.name %></td>
      <td><%= track.year %></td>
      <td><%= track.genre.name %></td>
      <td><%= track.length %></td>
      <td><%= track.size %></td>
      <td><%= track.bpm %></td>
      <td>Sound: <%= rating_for track, "rating" %></td>
      <td><%#= image_tag 'playbutton.png', :class => "playbutton", :data => { :track_id => track.id} %>
          <%#= image_tag 'stopbutton.png', :class => "stopbutton", :data => { :track_id => track.id} %></td>
      <%# @track = track %>
      <%#= f.fields_for "playlist[playlist_tracks_attributes][]" do |p| %>
      <td><%#= check_box_tag("playlist[playlist_tracks_attributes][][track_id]", track.id) %></td>
      <td><%#= check_box_tag("playlist[playlist_tracks_attributes][][track_id]", track.id) %></td>
     </tr>
   </tbody>


    <% end %>
    <%# end %>
</table>

    <!-- Footer -->

app/views/playlists/create.js.erb
create.js.erb

app/views/playlists/index.html.erb
<h1>PlayLists</h1>
  <%# binding.pry %>
  <% @playlists.each do |pl| %>
  <table id="draggable-<%= pl.id %>" class="ui-widget-content">
    <tr>
        <th><%= pl.name %></th>
        <th> Playlist: <%#= rating_for pl, "playlist" %></th>
    </tr>

    <tr>
      <% pl.tracks.each do |t| %>
     <tr><td><%= t.title %></td></tr>
      <% end %>
      <tr><td><%= link_to "See Comments", library_playlist_path(@library.id, pl.id) %></td></tr>
  <% end %>

  </table>

<%= link_to 'Create Playlist', new_library_playlist_path(@library.id) %> |
<%= link_to 'Back', library_path(current_user.library) %>